### ISSUE TITLE
Desapareixen les connexions quan es connecten fibres alineades

### ISSUE THREAD

**Issue by mameijeiras** [gisce/fiber-diagram#19]
El problema és que a part que desapareixen les línies, no es poden desconnectar les fibres i s'ha de refrescar la pàgina. Si es desa, apareix igual. Adjunto captures de com ho he reproduït a l'entorn de [Telecos Test](https://webclient.telecos.gisce.dev/) (primera captura) i en local (segona captura).

El comportament és lleugerament diferent en local, ja que en local quan connectes dues fibres es crea la bola de la connexió més gran, no sé si es tracta d'un cas previst però entenc que s'haurien de mostrar sempre les connexions per tal de poder connectar i desconnectar les fibres @ecarreras 

[Enregistrament de pantalla des de 12-6-23 12:48:02.webm](https://github.com/gisce/fiber-diagram/assets/118173541/6d380c93-4e02-4480-886e-b5dfe0b7a290)

[Enregistrament de pantalla des de 12-6-23 12:48:24.webm](https://github.com/gisce/fiber-diagram/assets/118173541/a59812f1-5057-4795-908e-72b9ca37323f)

**Comment by mguellsegarra** [comment]
He estat revisant el component un cop migrat a vite, i em funciona bé a l'entorn 

https://beta.webclient.telecos.gisce.dev/
@mameijeiras pots fer-hi una ullada per si ho pots reproduïr?

El https://webclient.telecos.gisce.dev/ queda pendent de fer el merge per a que utilitzi el nou component.

**Comment by mameijeiras** [comment]
@mguellsegarra amb el primer CTO es pot veure fàcilment agafant els dos primers ports de dalt

**Comment by ecarreras** [comment]
El problema és quan es pensa que vols fer un "tub a tub" perquè totes les fibres d'un costat les fusiones amb totes les de l'altre costat, però el tub de l'altre costat té més fibres.

![image](https://github.com/gisce/fiber-diagram/assets/294235/374c9d8c-994e-4a07-9c09-197f9b1a1c42)

**Comment by mguellsegarra** [comment]
Per fi he pogut reproduïr el que comentaveu, per si us passa mai, tenia extensions de bloqueig d'anuncis i trackers que feien que no pogués clicar depenent de en quina fibra tocava... Investigo ara sí què fa malament amb el tema d'ajuntar els tubs.

**Comment by ecarreras** [comment]
Testejat a develop i funciona bé! 🚀

**Comment by mameijeiras** [comment]
Moltes gràcies, @mguellsegarra!

**Comment by mguellsegarra** [comment]
@ecarreras @mameijeiras 
Us sembla si ho passo a `main`?

**Comment by ecarreras** [comment]
Si si, i tant

**Comment by mguellsegarra** [comment]
Ara estava fent proves, i crec que no es poden colapsar mai els tubs, vaig a revisar-ho abans de passar res a main.

**Comment by mguellsegarra** [comment]
He pujat una nova versió a l'entorn de develop, ara ja es col·lapsen els tubs quan vagin totes les fibres a un altre tub i coincideixin en número.

@ecarreras @mameijeiras Si voleu fer una prova ràpida per assegurar i ho passem a main

**Comment by mameijeiras** [comment]
@mguellsegarra ho he provat al `CTO B` i no funciona del tot bé, sembla que no es poden desconnectar els cables:

[Enregistrament de pantalla des de 16-6-23 11:03:25.webm](https://github.com/gisce/fiber-diagram/assets/118173541/9731aaed-3ed0-4d1c-a2cb-c0c460d98006)

**Comment by ecarreras** [comment]
Jo crec que ja va guai! 🚀 
![image](https://github.com/gisce/fiber-diagram/assets/294235/cbaf928c-3710-4add-91a9-8968cee895e4)

**Comment by mguellsegarra** [comment]
Passat a `main` ! 💪

**Comment by mameijeiras** [comment]
> Passat a `main` ! muscle

Genial @mguellsegarra! Quan puguis revisa el que passa al CTO B, no es pot desfer una connexió tub a tub, suposo que deu estar relacionat.

**Comment by mguellsegarra** [comment]
> Quan puguis revisa el que passa al CTO B, no es pot desfer una connexió tub a tub, suposo que deu estar relacionat.

Ara ho reviso, crec que té a veure amb la detecció de canvis

**Comment by mguellsegarra** [comment]
@mameijeiras 

Ja he trobat què era. He pujat un fix a `develop` (entorns `beta`), per a que hi feu una ullada i un cop ho vegeu bé si voleu podem passar-ho a `main`.

Ja em dieu, merci! :) 

cc: @ecarreras

**Comment by mameijeiras** [comment]
> @mameijeiras
> 
> Ja he trobat què era. He pujat un fix a `develop` (entorns `beta`), per a que hi feu una ullada i un cop ho vegeu bé si voleu podem passar-ho a `main`.
> 
> Ja em dieu, merci! :)
> 
> cc: @ecarreras

@mguellsegarra Segueixo sense poder desfer la connexió al CTO B :'(

**Comment by mameijeiras** [comment]
@mguellsegarra Ara m'ha funcionat també!

**Comment by ecarreras** [comment]
Per mi perfecte 👍🏻

**Comment by mameijeiras** [comment]
@mguellsegarra @ecarreras aquesta issue ja es pot tancar, oi?

**Comment by mguellsegarra** [comment]
Sí, feel free!
