### ISSUE TITLE
Panell de connexions no detecta canvis

### ISSUE THREAD

**Issue by mameijeiras** [gisce/fiber-diagram#24]
Acostuma a passar al primer canvi, tant si es crea com si s'elimina una connexió. S'ha de fer un segon canvi al diagrama de connexions perquè el formulari detecti que hi ha hagut canvis i es pugui clicar al botó de desar.

S'adjunten dos vídeos amb exemples per reproduir la incidència:

[Enregistrament de pantalla des de 14-2-24 10:59:56.webm](https://github.com/gisce/fiber-diagram/assets/118173541/c145d12e-aa4f-448e-8a4d-bd7a2ec03050)

[Enregistrament de pantalla des de 14-2-24 11:01:29.webm](https://github.com/gisce/fiber-diagram/assets/118173541/e3428b02-d3d8-4f86-b460-ba8557adcccf)

**Comment by mguellsegarra** [comment]
Revisat, i aplicat un fix a [v3.0.0-alpha.34](https://github.com/gisce/webclient/releases/tag/v3.0.0-alpha.34), podries mirar-ho i em dius @mameijeiras ? Merci :)

**Comment by mameijeiras** [comment]
> Revisat, i aplicat un fix a [v3.0.0-alpha.34](https://github.com/gisce/webclient/releases/tag/v3.0.0-alpha.34), podries mirar-ho i em dius @mameijeiras ? Merci :)

Provat i funciona!

**Comment by mguellsegarra** [comment]
Passat a `main`, disponible a la [Release - v2.2.9](https://github.com/gisce/webclient/releases/tag/v2.2.9)
