### ISSUE TITLE
Exportar panell de connexions al GIS

### ISSUE THREAD

**Issue by mameijeiras** [gisce/fiber-diagram#27]
S'ha d'exportar el component per permetre que es pugui visualitzar el panell de connexions des del formulari del CTO del `webgis`.

![image](https://github.com/gisce/fiber-diagram/assets/118173541/09c8501b-fa17-425d-ad4d-3249d17d79b6)
![image](https://github.com/gisce/fiber-diagram/assets/118173541/c94a3e09-f3b3-442a-b4a2-4fd35fb843f6)

**Comment by mguellsegarra** [comment]
@ecarreras @mameijeiras 
Això és el que vam parlar de fer que es pogués instanciar el component en un projecte sense React?

**Comment by ecarreras** [comment]
Si, però diria que al final només ho vam parlar però no fer

**Comment by ecarreras** [comment]
De moment serà mode readonly, per tant li passarem per "prop" el json amb les dades, més endavant ja mirarem com fer pq li passem les dades i amb un "onchange" ens retorni el json modificat :P

**Comment by mguellsegarra** [comment]
He fet una prova ràpida, perquè ho pogueu provar 🚀 

Teniu un exemple [aquí](https://github.com/gisce/fiber-diagram-vanilla-example).

La llibreria de fiber-diagram té una branch `vanilla` on hi consten els canvis que s'han de fer a l'hora de fer la build de la llibreria, ja que en aquest cas, cal arrossegar React, antd, React-Konva i totes les llibreries que s'utilitzen.

Cada vegada que es faci una nova versió de fiber-diagram caldrà que actualitzem el fitxer minificat de la llibreria pel GIS. 

Ho anem parlant i pensant quina serà la millor forma.

@ecarreras @mameijeiras

**Comment by mameijeiras** [comment]
@mguellsegarra No puc veure l'enllaç :crying_cat_face:

**Comment by mguellsegarra** [comment]
> @mguellsegarra No puc veure l'enllaç 😿

És un repositori de Github de Gisce, el qual té `giscers` als permisos... I tu hi ets... https://github.com/orgs/gisce/teams/giscers?query=mam

Què estrany!

**Comment by ecarreras** [comment]
@mguellsegarra genial 👏🏻 ara miro els permisos @mameijeiras.

@mguellsegarra es podria fer que el vanilla.js es crees com a release dins d'aquest repo?

**Comment by mguellsegarra** [comment]
> @mguellsegarra es podria fer que el vanilla.js es crees com a release dins d'aquest repo?

ho miro!

**Comment by mguellsegarra** [comment]
Com ho veieu @ecarreras ?

https://github.com/gisce/fiber-diagram/releases
https://github.com/gisce/fiber-diagram/releases/download/v2.1.0-alpha.5/fiber-diagram.vanilla.es.js

![Screenshot 2024-03-21 at 09 15 16](https://github.com/gisce/fiber-diagram/assets/5711443/46eadc83-357e-45c8-a62e-d766d4b92c52)

**Comment by mameijeiras** [comment]
@mguellsegarra @ecarreras comentar que ja està disponible una primera implementació de la visualització del panell `fiber-diagram` des del `webgis`:

![image](https://github.com/gisce/fiber-diagram/assets/118173541/afb57c9f-8a17-4ef9-ab3a-92ca652ea2ce)
![image](https://github.com/gisce/fiber-diagram/assets/118173541/2375a3f0-210e-49a8-b24c-9f3ce1a63e01)

Entenc que potser s'hauria de fer alguna millora però que en principi aquesta issue ja es podria tancar :rocket:
