### ISSUE TITLE
Mostrar més gran la posició del cable

### ISSUE THREAD

**Issue by mameijeiras** [gisce/fiber-diagram#28]
Dintre del que sigui possible, ampliar la mida de la posició del cable dins la caixa per facilitar la llegibilitat a l'usuari.

![image](https://github.com/gisce/fiber-diagram/assets/118173541/68cd9361-298d-40d6-abbd-a86e2a28e63b)

**Comment by mguellsegarra** [comment]
@mameijeiras cal fer més gruixut el wire? No acabo de veure clar quin seria el canvi de:

```
ampliar la mida de la posició del cable dins la caixa 
```

**Comment by mameijeiras** [comment]
@mguellsegarra Només la mida de la font de la posició: "1", "2", etc.

**Comment by mguellsegarra** [comment]
@mameijeiras 

Com ho veus?

Abans:
![Screenshot 2024-03-20 at 13 48 55](https://github.com/gisce/fiber-diagram/assets/5711443/29b9da9d-d7f3-49ef-9c81-87f9fcd7ec00)

Després:
![Screenshot 2024-03-20 at 13 48 46](https://github.com/gisce/fiber-diagram/assets/5711443/e54fb20b-8504-4092-9f0f-6e932e66e8ea)

**Comment by mameijeiras** [comment]
Jo crec que suficient, no @ecarreras? És una petició d'un client perquè entenem que ho faran servir des d'una tablet i amb la mida anterior se'ls feia una mica petit.

**Comment by mguellsegarra** [comment]
Fet, aplicat a `alpha` v3.0.0-alpha.51  per a que ho proveu, i un cop validat ho passem a `main` si ho creieu?

@mameijeiras

**Comment by mameijeiras** [comment]
Validat! :rocket: 

De moment ja està bé així, però segons parlat amb l'@ecarreras potser en un futur interessaria que s'aprofités tot l'ample del cable perquè destaqués encara més.

**Comment by mameijeiras** [comment]
:eyes: Petició meva a veure si es pot fer abans d'integrar: que la mida del text sigui com abans si no està definida la posició, si no és un número crec que queda potser massa gran @mguellsegarra

**Comment by mguellsegarra** [comment]
Fet @mameijeiras !

Vigent aquest canvi a la [3.0.0-alpha.55](https://github.com/gisce/webclient/compare/v3.0.0-alpha.54...v3.0.0-alpha.55)

Ja em dius i ho traspassem.

**Comment by mguellsegarra** [comment]
Traspassat! Vigent a [v2.2.15](https://github.com/gisce/webclient/releases/tag/v2.2.15)
