### ISSUE TITLE
Amagar `ids` dels Splitters

### ISSUE THREAD

**Issue by mameijeiras** [gisce/fiber-diagram#29]
Amagar els `ids` dels Splitters de la mateixa manera que als cables, mostrar únicament la "boleta".

![image](https://github.com/gisce/fiber-diagram/assets/118173541/a061bd62-736f-4e47-b7bf-904d07bc6f22)

**Comment by mguellsegarra** [comment]
Fet, aplicat a `alpha` v3.0.0-alpha.51  per a que ho proveu, i un cop validat ho passem a `main` si ho creieu?

@mameijeiras

**Comment by mameijeiras** [comment]
Validat! :rocket: 

PD: Ja he pogut veure com queden els Patch Panels :partying_face:
