### ISSUE TITLE
Ressaltar fibra seleccionada

### ISSUE THREAD

**Issue by mameijeiras** [gisce/fiber-diagram#30]
S'ha de ressaltar d'alguna manera la fibra seleccionada per distingir-la de la resta, ja que quan hi ha moltes fibres en un mateix CTO es fa complicat veure quina connexió s'està modificant. Per exemple, es podria fer com al GIS quan selecciones un cable.

**Comment by mguellsegarra** [comment]
@mameijeiras osti, podries passar-me un screenshot de com ho feu al GIS per ressaltar el cable?

**Comment by mameijeiras** [comment]
@mguellsegarra Aquí tens:

[Enregistrament de pantalla des de 22-5-24 14:10:13.webm](https://github.com/gisce/fiber-diagram/assets/118173541/dddb4948-624d-409e-9cc0-5fc1a0ff2cba)

**Comment by mguellsegarra** [comment]
@mameijeiras com selecciones una fibra al component actual?

L'única interacció que veig jo ara mateix és quan apretes sobre el punt de fusió per desfer una connexió:

![CleanShot 2024-05-23 at 09 49 15](https://github.com/gisce/fiber-diagram/assets/5711443/41c8e2ce-0e56-4faa-8b01-9a6d35d600ab)

I quan apretes sobre una fibra no connectada per anar a connectar-la amb una altra:

![CleanShot 2024-05-23 at 09 49 24](https://github.com/gisce/fiber-diagram/assets/5711443/30e8f5a2-d833-4372-963e-d52909ddbc82)

Son aquests casos als que fan referència i on volen veure la fibra ressaltada, d'alguna manera?

**Comment by mameijeiras** [comment]
@mguellsegarra entenc que hauria d'aplicar com a mínim en el primer cas, quan vols eliminar una connexió que es ressaltin les fibres que queden afectades.
Com ho veieu @ecarreras @tinogis?

**Comment by mameijeiras** [comment]
@mguellsegarra Jo crec que bé, a mi m'agrada!
Com ho veieu @ecarreras @tinogis?

**Comment by ecarreras** [comment]
Perfecte

**Comment by mguellsegarra** [comment]
Ho he pujat a `alpha` - [v3.0.0-alpha.72](https://github.com/gisce/webclient/releases/tag/v3.0.0-alpha.72) per a que li feu una ullada en directe ;)

Ja em dieu i ho passem a `main`

**Comment by mguellsegarra** [comment]
Què preferiu, que es vegi el ressaltat amb color blanc com fins ara, però que en les fibres blanques es vegi d'un altre color, o seleccionem un altre color per a tot el ressaltat ?

Teniu un llistat dels possibles colors que poden tenir les fibres? O ho pot canviar l'usuari?

**Comment by mguellsegarra** [comment]
Ajustat! Feu-hi una ullada, disponible a [v3.0.0-alpha.77](https://github.com/gisce/webclient/releases/tag/v3.0.0-alpha.77)

**Comment by mameijeiras** [comment]
@mguellsegarra perfecte, així es veu bé en tots els casos. Jo per mi ho podem marcar com a `To integrate` si us sembla bé @ecarreras @tinogis

**Comment by ecarreras** [comment]
Endavant!!

**Comment by mguellsegarra** [comment]
Traspassat ! 

Vigent a la [2.3.5](https://github.com/gisce/webclient/compare/v2.3.4...v2.3.5) ;)
